name: sapt-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - async-timeout==5.0.1
      - attrs==25.3.0
      - Brotli
      - certifi
      - charset-normalizer
      - click==8.2.0
      - colorama==0.4.6
      - datasets==2.14.6
      - dill==0.3.7
      - filelock
      - frozenlist==1.6.0
      - fsspec==2023.10.0
      - gmpy2
      - huggingface-hub==0.31.2
      - idna
      - Jinja2
      - joblib==1.5.0
      - loralib==0.1.2
      - MarkupSafe
      - mkl-service==2.4.2
      - mkl_fft
      - mkl_random
      - mpmath
      - multidict==6.4.3
      - multiprocess==0.70.15
      - networkx
      - numpy
      - packaging==25.0
      - pandas==2.2.3
      - pillow
      - propcache==0.3.1
      - psutil==7.0.0
      - pyarrow==20.0.0
      - PySocks
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - PyYAML
      - regex==2024.11.6
      - requests
      - safetensors==0.5.3
      - six==1.16.0
      - sympy==1.13.1
      - tokenizers==0.13.3
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.30.2
      - typing_extensions
      - tzdata==2025.2
      - urllib3
      - win-inet-pton
      - xxhash==3.5.0
      - yarl==1.20.0
      - nltk==3.8.1
